# fly.toml app configuration file generated for hcoins on 2023-08-21T18:23:48+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hcoins"
primary_region = "lhr"
kill_signal = "SIGINT"
kill_timeout = "5s"